version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine 
    ports:
    - target: 80
      published: 80 
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  flask-app:
    container_name: flask-app
    image: trio-task-flask:latest 
    build: ./flask-app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mysql: 
    container_name: mysql 
    image: trio-task-db:latest
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-db
